### PR TITLE
Workflow improvements

### PR DESCRIPTION
**Pull request by andy-berry-dev**
@leggetter can you take a look at this and let me know if there are any extra improvements that need to be made before Tuesday?
- BRJS path is now taken as a property for the init task
  - e.g. `./gradlew init -Pbrjs=/some/path/to/sdk`
- now checks that the path supplied for BRJS is valid
- new task (`copyToBrjs`) to copy the jar in to brjs conf/java dir
- correctly generates the eclipse/idea classpath, unfortunately this has to be done as a separate run of gradle. So the workflow is now `gradle init` followed by `gradle eclipse`
- now adds the src jar to the classpath (for Eclipse only)

### CODE REVIEW

**Comment by andy-berry-dev** [comment]
if you want to test using the src jar you'll need to use bundler-exploration branch of brjs. BladeRunnerJS/brjs@0237b7717fc45eb272cf00f7326eaa5b2bc6c01c is the change to start generating the src jar

**Comment by andy-berry-dev** [comment]
@leggetter made a change so the brjs property is now the dir for the root of brjs rather than the sdk. It also now checks that the dir supplied is valid and contains and sdk dir.

**Comment by leggetter** [comment]
@andyberry88 Any reason you can see that I get the WARNING?

```
./gradlew init -Pbrjs=/Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace/

## WARNING: You are attempting to run a command(s) before initialising this project. You should first run the 'init' task. ##

:init

gradle.properties and src & resources directories created successfully, you can now delete the 'init' task from build.gradle.
You should now run './gradlew eclipse' or './gradlew idea' to generate the project files for your IDE and can then run tasks to compile and test your project.
Run './gradlew tasks' to view a list of tasks available via Gradle or read README.md for more info.


BUILD SUCCESSFUL

Total time: 4.219 secs
```

**Comment by leggetter** [comment]
Also get an exception when running `./gradlew eclipse`:

```
: ./gradlew eclipse
:eclipseClasspath
:eclipseJdt
:eclipseProject
:eclipse
Warning: Exception was thrown when attempting to add the brjs-core src jar to the classpath. This was probably because the src jar doesn't exist.
The exception was: 
>> java.lang.IllegalStateException: Expected directory '/Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace' to contain exactly one file, however, it contains no files.

BUILD SUCCESSFUL

Total time: 4.137 secs
```

Full step to reproduce:

```
curl -L https://github.com/BladeRunnerJS/brjs-plugin-bootstrap/archive/workflowImprovements.zip > start.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    208      0 --:--:-- --:--:-- --:--:--   208
100 52785  100 52785    0     0  29408      0  0:00:01  0:00:01 --:--:-- 51000
[] leggetter@~/caplin/demos: unzip start.zip
Archive:  start.zip
116983842fbf2ac386b65d2bf0efcc6d15c4c3f5
   creating: brjs-plugin-bootstrap-workflowImprovements/
  inflating: brjs-plugin-bootstrap-workflowImprovements/.gitignore  
  inflating: brjs-plugin-bootstrap-workflowImprovements/README.md  
  inflating: brjs-plugin-bootstrap-workflowImprovements/build.gradle  
   creating: brjs-plugin-bootstrap-workflowImprovements/gradle/
   creating: brjs-plugin-bootstrap-workflowImprovements/gradle/wrapper/
  inflating: brjs-plugin-bootstrap-workflowImprovements/gradle/wrapper/gradle-wrapper.jar  
  inflating: brjs-plugin-bootstrap-workflowImprovements/gradle/wrapper/gradle-wrapper.properties  
  inflating: brjs-plugin-bootstrap-workflowImprovements/gradlew  
  inflating: brjs-plugin-bootstrap-workflowImprovements/gradlew.bat  
[] leggetter@~/caplin/demos: mv brjs-plugin-bootstrap-workflowImprovements ListAppsPlugin
[] leggetter@~/caplin/demos: cd ListAppsPlugin
[] leggetter@~/caplin/demos/ListAppsPlugin: ./gradlew init -Pbrjs=/Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace/

## WARNING: You are attempting to run a command(s) before initialising this project. You should first run the 'init' task. ##

:init

gradle.properties and src & resources directories created successfully, you can now delete the 'init' task from build.gradle.
You should now run './gradlew eclipse' or './gradlew idea' to generate the project files for your IDE and can then run tasks to compile and test your project.
Run './gradlew tasks' to view a list of tasks available via Gradle or read README.md for more info.


BUILD SUCCESSFUL

Total time: 1.972 secs
[] leggetter@~/caplin/demos/ListAppsPlugin: ./gradlew eclipse
:eclipseClasspath
:eclipseJdt
:eclipseProject
:eclipse
Warning: Exception was thrown when attempting to add the brjs-core src jar to the classpath. This was probably because the src jar doesn't exist.
The exception was: 
>> java.lang.IllegalStateException: Expected directory '/Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace' to contain exactly one file, however, it contains no files.

BUILD SUCCESSFUL

Total time: 4.176 secs
```

**Comment by andy-berry-dev** [comment]
The warning when running 'gradle init' is because the project hasn't been initialised yet. I need to add a note about ignoring it if you're running the init task.

The exception for the src jar means it couldn't find the jar to add to the classpath. Did you rebuild brjs from src using the latest bundler-exploration branch?

**Comment by leggetter** [comment]
Yeah, built bundler-exploration.

```
[] leggetter@~/caplin/demos/ListAppsPlugin: ls /Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace
LICENSE     apps        generated   licenses    test-results
README.txt  conf        js-patches  sdk
[] leggetter@~/caplin/demos/ListAppsPlugin: ls /Users/leggetter/caplin/git/brjs/cutlass-sdk/workspace/sdk/
brjs            jsdoc-templates     system-applications version.txt
brjs.cmd        jsdoc-toolkit       templates
docs            libs            test-results
```

**Comment by andy-berry-dev** [comment]
@leggetter can you print the outcome from `ls sdk/docs/src`?

**Pull request merged**
